### ISSUE TITLE
Marlin Modifications for GEN7

### ISSUE THREAD

**Issue by NonaSuomy** [Nightfly1704/Gen7-_ExtensionBoard_LCD_SD_FAN#3]
Can you add your code modifications of marlin (pins.h,conf) to get this working as the GEN7 is missing anything to do with an LCD in pins.h etc for it (1.4)?

**Comment by Nightfly1704** [comment]
Hi, I am using Repetier Firmware and uploaded the Modifications from Repetier Firmware and a List of Pin assignments .. had a short look at Marlin Firmware and will try to add the modifications to it but didn't have time at this moment. I will try to add it the next week. pins.h looks similar to Repetier. Configuration should be ULTRA_LCD and ULTIPANEL but didnt find the pin config for this.

**Comment by Nightfly1704** [comment]
The project isn't developed any further
